### ISSUE TITLE
Create Jaeger Helm Chart

### ISSUE THREAD

**Issue by dvonthenen** [TheCodeTeam/roadmap#195]
Just like it says... create a Jaeger Helm Chart and be able to configure any appropriate flags that are available/significant.

**Comment by dvonthenen** [comment]
Started looking into implementing this.

**Comment by clintkitson** [comment]
Any status update here?

**Comment by akutz** [comment]
Yes. Today...*We're cancelling the apocalypse!* https://youtu.be/xsUGU-49I1I

No Jaeger will break this line!

**Comment by clintkitson** [comment]
Funny @akutz =)

@dvonthenen I just noticed the Jaeger team uses Trello to track this story.

https://trello.com/c/3z3Be5Wp/44-kubernetes-helm-charts-templates

**Comment by dvonthenen** [comment]
After fighting through numerous issues with integrating the Cassandra chart into Jaeger. I finally have an acceptable solution and have posted the PR https://github.com/kubernetes/charts/pull/2078 for the initial release of the Jaeger chart.

**Comment by dvonthenen** [comment]
Will continue to monitor the PR for feedback. Marking this "done" for right now. Will close when the PR is merged.

**Comment by dvonthenen** [comment]
PR has been merged!
