### ISSUE TITLE
Personal Blog: Jaeger Helm Chart ElasticSearch Support

### ISSUE THREAD

**Issue by dvonthenen** [thecodeteam/roadmap#204]
Just like the title says...

**Comment by dvonthenen** [comment]
This is in progress. Using the changes in the ES chart in offline mode to continue working on this.

**Comment by dvonthenen** [comment]
PR https://github.com/kubernetes/charts/pull/2684 is open. Need to change the blog blog since I got the ES chart working.

**Comment by jpkrohling** [comment]
Would you like to publish it on the Jaeger's blog?

**Comment by dvonthenen** [comment]
@jpkrohling Definitely! That would be awesome!

**Comment by dvonthenen** [comment]
Blog has been reviewed. Waiting to post.

**Comment by jpkrohling** [comment]
The blog post on Jaeger publication has been scheduled for next Monday.

**Comment by dvonthenen** [comment]
@jpkrohling Awesome! Sounds good!

**Comment by dvonthenen** [comment]
Blog is posted:
https://medium.com/jaegertracing/jaeger-helm-chart-simplifying-deployment-48056217730f
