### ISSUE TITLE
Personal Blog: Jaeger sidecar deployments support

### ISSUE THREAD

**Issue by dvonthenen** [thecodeteam/roadmap#205]
Just like the title says...

**Comment by kacole2** [comment]
@dvonthenen i know you said last week you were working on this. is it complete? would you like to bring it on the team blog?

**Comment by dvonthenen** [comment]
@kacole2  I haven't started on this yet. I am getting hung up with some ElasticSearch issues that are affecting both the Jaeger chart work (adding support for ES) as well as the Fluentd (it uses ES as the backing store). I might have to table both of these things which means I might be able to start this as it is independent of ES.

**Comment by dvonthenen** [comment]
User in the community contributed this PR
