### ISSUE TITLE
 Research Istio

### ISSUE THREAD

**Issue by dvonthenen** [thecodeteam/roadmap#221]
Learn about Istio and deploy into a Kubernetes cluster to understand its functionality. Would be helpful to deploy applications in different deployments that make use of Istio.

**Comment by kacole2** [comment]
you treading in my playground homie?

**Comment by dvonthenen** [comment]
@kacole2 LOL. Naw, I just need to know how to deploy it so I can update their chart to optionally use Jaeger instead of Zipkin.

**Comment by dvonthenen** [comment]
Deployed istio chart onto a kubernetes 1.8 cluster. Marking completed.
