### ISSUE TITLE
KubeCon EU18 CFP

### ISSUE THREAD

**Issue by clintkitson** [thecodeteam/roadmap#223]
#### Submitted topics
* [x] Vlad
* [x] Clint
* [x] Travis
* [x] Chris
* [x] David

#### Notes from our meeting
kubecon eu
- storage
    - distributed storage.. and crypto (NEBL, SUB, SIAC, DAD, STORJ)
    - making csi plugins
    - csi plugins soup to nuts
- indentity
    - apps that consume their own storage
- on-prem/install/enterprise
- CO comparison talk
- community building
- serverless
- interesting things w k8s

**Comment by dvonthenen** [comment]
I have updated my CFPs abstracts based on feedback from our meeting and submitted them.

**Comment by codenrhoden** [comment]
I have submitted 2 CFPs. Feedback incorporated as well.
